config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    member do
      put :add_to_cart
    end
  end

  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  resources :orders, only: [:create] do
    member do
      get :pay
    end

    collection do
      post :finish
    end
  end

  namespace :api do
    namespace :v1 do
      post :pay2go_callback, to:"pay2go#callback"
    end
  end

  root "pages#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart

  attr_reader :items

  def initialize( items = [])
    @items = items
  end

  def add_item(product_id)

    item = items.find { |x| x.product_id == product_id }

    if item
      item.increment
    else
      items << CartItem.new(product_id)
    end

  end

  def empty?
    items.empty?
  end

  def total_price
    items.reduce(0) { |sum , item| sum + item.total_price }
  end

  def serialize
    result = items.map { |item| {"product_id" => item.product_id,
                                 "quantity" => item.quantity} }

    { "items" => result }
  end



  def self.build_from_hash(hash)
      all_items = []
      if hash && hash["items"]
        all_items = hash["items"].map do |item|
          CartItem.new(item["product_id"], item["quantity"])
        end
      end
      new all_items
  end

end

app/models/cart_item.rb
class CartItem
  attr_reader :product_id, :quantity

  def initialize(product_id, quantity = 1 )
    @product_id = product_id
    @quantity = quantity
  end

  def increment
    @quantity += 1
  end

  def product
    Product.find_by(id: product_id)
  end

  def total_price
    product.price * quantity
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  validates :address, presence: true
  # validates_of address

  # instance methods
  def serial_generator
    "OD#{id.to_s.rjust(10, "0")}"
  end

  def amount
    order_items.reduce(0) { |sum, item| sum + item.total_price }
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/pay2go_controller.rb
class Api::V1::Pay2goController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:callback]

  def callback
    raw = JSON.parse(params["JSONData"])
    result = JSON.parse(raw["Result"])
    trade_number = result["TradeNo"]
    check_code = result["CheckCode"]
    order_id = result["MerchantOrderNo"].to_i

    order = Order.find_by(id: order_id)

    if check_code == valid_check_code(order, trade_number)
      render text: "ok"
    else
      fail
    end
  end

  private

  def valid_check_code(order, trading_number)
    hash_key = "hZUa6EYiMjDPNtQowoSc4Cgmc5WIwkbO"
    hash_iv = "j5YqKWIxgmm3Pcrl"
    fields_string = {
      Amt: order.amount,
      MerchantID: "32237946",
      MerchantOrderNo: order.id,
      TradeNo: trading_number
    }.sort.map { |k, v| "#{k}=#{v}" }.join("&")

    Digest::SHA256.hexdigest("HashIV=#{hash_iv}&#{fields_string}&HashKey=#{hash_key}").upcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_cart

  private

  def set_cart
    @cart = Cart.build_from_hash(session["my_cart_session"])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end

  def checkout
    @order = Order.new
  end
end

app/controllers/orders_controller.rb
require "digest"

class OrdersController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:finish]

  def create
    @order = Order.new(order_params)

    @cart.items.each do |item|
      @order.order_items.build(product_id: item.product.id, quantity: item.quantity)
    end
    if @order.save
      # 1.購物車清空
      session["my_cart_session"] = nil

      # 2.轉往智付寶
      redirect_to pay_order_path(@order)
    else
      render "carts/checkout"
    end
  end

  def pay
    @order = Order.find_by(id: params[:id])
    redirect_to root_path unless @order

    @merchant_id = "32237946"
    @return_url = finish_orders_url
    @notify_url = api_v1_pay2go_callback_url
    @check_value = check_value(@order)
  end

  def finish
    render text: "finish"
  end

  private

  def order_params
    params.require(:order).permit(:name, :tel, :address)
  end

  def check_value(order)
    hash_key = "hZUa6EYiMjDPNtQowoSc4Cgmc5WIwkbO"
    hash_iv = "j5YqKWIxgmm3Pcrl"
    fields_string = {
      Amt: order.amount,
      MerchantID: @merchant_id,
      MerchantOrderNo: order.id,
      TimeStamp: order.created_at.to_i,
      Version: "1.2"
    }.sort.map { |k, v| "#{k}=#{v}" }.join("&")

    Digest::SHA256.hexdigest("HashKey=#{hash_key}&#{fields_string}&HashIV=#{hash_iv}").upcase
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :add_to_cart]

  # GET /products
  # GET /products.json
  def index
    @products = Product.page(params[:page]).per(10)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_to_cart
    @cart.add_item(@product.id)
    session["my_cart_session"] = @cart.serialize
    redirect_to products_path, notice: "已將 #{@product.title}加到購物車!!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gender_display(gender)
    case gender
    when 1
      "男"
    when 2
      "女"
    else
      "其他"
    end
  end

  def my_link_to(label, link)
    link_to lanel, link, class: "btn btn-default"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/carts/_cart.html.slim
.panel.panel-default
  .panel-heading
    | 購物車
  .panel-body
    table.table.table-hover
      thead
        tr
          th 商品
          th 數量
          th 單價
          th 小計
      tbody
        - @cart.items.each do |item|
          tr
            td = item.product.title
            td = item.quantity
            td = item.product.price
            td = item.total_price
      tfoot
        tr
          td colspan=3 總價
          td = @cart.total_price

app/views/carts/checkout.html.erb
<%= render partial: "shared/cart_list", locals: {cart: @cart} %>


 <%= simple_form_for @order do |f| %>
  <%= f.input :name %>
  <%= f.input :tel %>
  <%= f.input :address %>
  <div class="btn-group">
    <%= link_to '回上頁', :back, class:"btn btn-default btn-lg" %>
    <%= f.submit class:"btn btn-danger btn-lg"%>
  </div>
<% end %>
  <br />
  <br />

app/views/carts/show.html.slim
= render partial: "shared/cart_list", locals: {cart: @cart}

.btn-group
  = link_to "繼續選購", products_path, class: "btn btn-default btn-lg"
  = link_to "結帳", checkout_cart_path, class: "btn btn-danger btn-lg"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5AppTemplate</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= render "shared/flash_message" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/pay.html.erb
<form method="post" action="https://capi.pay2go.com/MPG/mpg_gateway" id="pay2go_form">
  <input type="hidden" name="MerchantID"      value="@merchant_id" />
  <input type="hidden" name="RespondType"     value="JSON" />
  <input type="hidden" name="CheckValue"      value="<%= @check_value %>" />
  <input type="hidden" name="TimeStamp"       value="<%= @order.created_at.to_i %>" />
  <input type="hidden" name="Version"         value="1.2" />
  <input type="hidden" name="MerchantOrderNo" value="<%= @order.id %>" />
  <input type="hidden" name="Amt"             value="<%= @order.amount %>" />
  <input type="hidden" name="ItemDesc"        value="XD寶石購買" />
  <input type="hidden" name="Email"           value="<%#= current_user.email %>" />
  <input type="hidden" name="LoginType"       value="0" />
  <input type="hidden" name="TradeLimit"      value="<%= 10.minutes %>" />
  <input type="hidden" name="ReturnURL"       value="<%= @returl_url %>" />
  <input type="hidden" name="NotifyURL"       value="<%= @notify_url %>" />
  <input type="hidden" name="EmailModify"     value="0" />
  <input type="hidden" name="CREDIT"          value="1" />
  <input type="hidden" name="VACC"            value="0" />
</form>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1>你好!</h1>
  <p>寶石鑑定商你一定賺很大!</p>
</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="jumbotron">
  <h1>你好</h1>
  <p>歡迎買寶石</p>
</div>

<h1>商品列表</h1>

<%= link_to 'New Product', new_product_path, class: "btn btn-success btn-lg"%>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to '加到購物車', add_to_cart_product_path(product), method: :put %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @products, theme: "twitter-bootstrap-3" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_cart.html.erb
<% unless @cart.empty? %>
  <li>
  <%= link_to cart_path do %>
    購物車
    <span class="badge"><%= @cart.items.count %></span>
  <% end %>
  </li>
<% end %>

app/views/shared/_cart_list.html.slim
.panel.panel-default
  .panel-heading
    | 購物車
  .panel-body
    table.table.table-hover
      thead
        tr
          th 商品
          th 數量
          th 單價
          th 小計
      tbody
        - cart.items.each do |item|
          tr
            td = item.product.title
            td = item.quantity
            td = item.product.price
            td = item.total_price
      tfoot
        tr
          td colspan=3 總價
          td = cart.total_price

app/views/shared/_flash_message.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= message %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">五百倍綠寶石</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <%= render partial: "shared/cart", local: {cart: @cart} %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>